### ISSUE TITLE
marioLevelLength Parameter setting

### ISSUE THREAD

**Issue by CIGbalance** [schrum2/GameGAN#4]
The marioLevelLength Parameter setting is a bit problematic:

- I assume the value of this parameter needs to change with the number of segments? Would be good to have that done automatically, in order to avoid problems where someone forgets to change that in the .bat file
- If you set the parameter wrong, it causes out of bound exceptions.

**Comment by CIGbalance** [comment]
```
[INFO] [GANThread] Comm:commSend will send [[-0.02192507803613064, 0.36217877625784145, 0.17723193205689158, -0.07959538211518469, -0.8178115878462389, 0.35855259939455064, -0.7757443196952014, -0.25970198872810557, 0.3166658604812085, 0.041606686598753884, 0.9198250710552067, -0.3908099870135804, -0.6233159602517682, -0.08058389721660575, -0.4992641504197044, 0.02604993925217247, -0.6695853799242539, -0.5969569466995104, 0.1291353599871916, 0.3603735521700808, 9.051189072728505E-4, 0.8932860519534109, -0.045393591932220145, 0.18109388359636602, -0.5107715106912576, -0.6498796535697766, 0.5472632770464911, 0.33176373317523256, -0.5897962247342701, 0.36271203645054606]] to GAN
processCommRecv:[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [12, 2, 2, 2, 2, 2, 10, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2], [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [10, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,7,2,2,2,2,2,2,2,2,2,2,2],[12,2,2,2,2,2,10,2,2,2,2,2,2,2,2,2,2,2,2,7,2,2,2,2,2,2,2,2],[0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[10,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 28, Size: 28
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at edu.southwestern.tasks.mario.level.MarioState.tileAtPosition(MarioState.java:66)
	at edu.southwestern.tasks.mario.level.MarioState.passable(MarioState.java:96)
	at edu.southwestern.tasks.mario.level.MarioState.getSuccessor(MarioState.java:125)
	at edu.southwestern.tasks.mario.level.MarioState.getSuccessor(MarioState.java:10)
	at edu.southwestern.util.search.State.getSuccessors(State.java:33)
	at edu.southwestern.util.search.GraphSearch.search(GraphSearch.java:45)
	at edu.southwestern.tasks.mario.MarioLevelTask.oneEval(MarioLevelTask.java:359)
	at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
	at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:82)
	at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:180)
	at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:324)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:406)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:563)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:534)
```

**Comment by CIGbalance** [comment]
I just realised, this error probably has nothing to do with the parameter setting but just the implementation of MarioState. But the issue with setting this appropriately still stands. So the issue should read now:

The marioLevelLength Parameter setting is a bit problematic:
* I assume the value of this parameter needs to change with the number of segments? Would be good to have that done automatically, in order to avoid problems where someone forgets to change that in the .bat file
